#!/usr/bin/env python3
"""
generate_reviews.py

Generates SQL to insert coherent, varied fake reviews for every restaurant
listed in `sql/insert_data.sql`.

Usage:
  python sql/generate_reviews.py [--offset 17600] [--per 5] [--out sql/insert_reviews.sql]

The script writes an INSERT file with `ON CONFLICT (id_ristorante,id_utente) DO NOTHING` so
it's safe to re-run on the same database.
"""

import argparse
import random
import datetime
import re
from pathlib import Path


def count_restaurants(insert_data_path: Path) -> int:
    txt = insert_data_path.read_text(encoding='utf-8')
    # Count how many INSERT INTO RistorantiTheKnife occurrences exist
    return len(re.findall(r"INSERT\s+INTO\s+RistorantiTheKnife\b", txt, flags=re.IGNORECASE))


POSITIVE = [
    'Exceptional creative cuisine! Highly recommend.',
    'Delicious food and attentive service.',
    'Beautiful presentation and outstanding flavors.',
    'Worth every penny, will return for special occasions.',
    'Amazing ambiance and perfect wine pairing.'
]

NEUTRAL = [
    'Good experience, nothing extraordinary.',
    'Solid dishes but some courses lacked punch.',
    'Overall pleasant, service was adequate.',
    'Pricey but acceptable for the quality.'
]

NEGATIVE = [
    'Poor service and some cold dishes, disappointing.',
    'Not what I expected, food was bland.',
    'Long waiting time and subpar execution.',
    'Would not recommend based on this visit.'
]


def choose_text_for_rating(rating: int, rnd: random.Random) -> str:
    if rating >= 5:
        return rnd.choice(POSITIVE)
    if rating == 4:
        # mostly positive but can be lightly critical
        return rnd.choice(POSITIVE + NEUTRAL)
    if rating == 3:
        return rnd.choice(NEUTRAL)
    return rnd.choice(NEGATIVE)


def make_timestamp(rnd: random.Random) -> str:
    days = rnd.randint(1, 180)
    dt = datetime.datetime.now() - datetime.timedelta(days=days)
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--offset', type=int, default=17600,
                   help='ID offset added to restaurant base IDs')
    p.add_argument('--per', type=int, default=5, help='Reviews per restaurant')
    p.add_argument('--out', type=Path, default=Path('sql/insert_reviews.sql'))
    p.add_argument('--data', type=Path, default=Path('sql/insert_data.sql'),
                   help='Path to insert_data.sql to count restaurants')
    args = p.parse_args()

    if not args.data.exists():
        raise SystemExit(f"insert_data.sql not found at {args.data}. Run csv_to_sql.py first.")

    n_rest = count_restaurants(args.data)
    rnd = random.Random(42)  # deterministic

    users = [1, 2, 3]
    ratings_pattern = [5, 4, 3, 4, 5]

    out_lines = []
    out_lines.append('-- Generated by generate_reviews.py')
    out_lines.append(f'-- Restaurants found: {n_rest}  |  offset: {args.offset}  |  reviews per restaurant: {args.per}')
    out_lines.append('')

    # Create grouped multi-row inserts per 100 restaurants to avoid huge single statement
    batch = []
    for base_id in range(1, n_rest + 1):
        restaurant_id = base_id + args.offset
        # make a small rnd per restaurant for variety
        r_rnd = random.Random(100000 + base_id)

        for i in range(args.per):
            rating = ratings_pattern[i % len(ratings_pattern)]
            text = choose_text_for_rating(rating, r_rnd)
            # ensure text does not contain single quote issues
            text_sql = text.replace("'", "''")
            uid = users[i % len(users)]
            ts = make_timestamp(r_rnd)
            batch.append(f"({restaurant_id}, {uid}, {rating}, '{text_sql}', '{ts}')")

        # flush batch every 500 rows to keep statements manageable
        if len(batch) >= 500:
            out_lines.append('INSERT INTO Recensioni (id_ristorante, id_utente, stelle, testo, data_inserimento) VALUES')
            out_lines.append(',\n'.join(batch) + '\nON CONFLICT (id_ristorante, id_utente) DO NOTHING;')
            out_lines.append('')
            batch = []

    if batch:
        out_lines.append('INSERT INTO Recensioni (id_ristorante, id_utente, stelle, testo, data_inserimento) VALUES')
        out_lines.append(',\n'.join(batch) + '\nON CONFLICT (id_ristorante, id_utente) DO NOTHING;')
        out_lines.append('')

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text('\n'.join(out_lines), encoding='utf-8')
    print(f'Wrote {args.out} ({n_rest * args.per} reviews)')


if __name__ == '__main__':
    main()

